- name: group variable priority ordering example play
  hosts: all
  gather_facts: false

  tasks:
  - name: show assigned group variables
    vars:
      msg: |
          http_port:{{ hostvars[inventory_hostname]['http_port'] | default("undefined")}}
          proxy_timeout:{{ hostvars[inventory_hostname]['proxy_timeout'] | default("undefined") }} 
          ansible_port:{{ hostvars[inventory_hostname]['ansible_port'] | default("undefined")}}
    
    ansible.builtin.debug:
      msg: "{{ msg.split('\n') }}"