#!/home/yash/ansible/myansible/bin/ansible-playbook
- name: playing with ansible
  hosts: centos
  gather_facts: true
  remote_user: remote_user
  become: 'yes'
  become_user: root

  tasks:
    - name: creating files
       

