#!/home/yash/ansible/myansible/bin/ansible-playbook
- name: Installing WebServer
  hosts: centos
  remote_user: remote_user
  become: 'yes'
  become_user: root

  tasks:
    - name: Ensure Apache is at the Latest Version
      yum:
        name: httpd
        state: absent
    - name: Ensure Apache is Running
      service:
        name: httpd
        state: stopped
